#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm and pnpm into PATH
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Run checks
pnpm lint
pnpm typecheck
pnpm format:check
